---
# tasks file for nodejs

- name: remove nodejs
  yum:
    name: "{{ item }}"
    enablerepo: epel
    state: absent
  with_items:
    - nodejs
    - npm

- name: import nodejs repo 11.x
  shell: curl -sL https://rpm.nodesource.com/setup_11.x | bash -

- name: install nodejs 11.2.0
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - nodejs

#- name: Installing node and npm
#  yum:
#    name: "{{ item }}"
#    enablerepo: epel
#    state: installed
#  with_items:
#    - nodejs
#    - npm
