---
# tasks file for jenkins
- name: Import Jenkins GPG key
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

- name: Add Jenkins repository
  yum_repository:
    name: jenkins
    description: jenkins repository
    baseurl: https://pkg.jenkins.io/redhat-stable
    enabled: no
    gpgcheck: yes

- name: Install Jenkins
  yum:
    name: jenkins
    enablerepo: jenkins
    state: present

- name: Start Jenkins
  service:
    name: jenkins
    enabled: yes
    state: started

